--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/provsalt/LightningDeath
branches:
- master
projects:
  LightningDeath:
    path: ""
    libs:
    - src: JackMD\UpdateNotifier\UpdateNotifier
      version: ^1.0.0
  
...
