name: LightningDeath
api: 3.14.0
authors:
  - provsalt
  - muqsit
version: 1.2.3
mcpe-protocol: [407, 408, 419, 422]
website: saltcraft.xyz
main: provsalt\lightningdeath\Loader
permissions:
  lightningdeath.bypass:
    default: false
