name: LightningDeath
api: 3.15.0
authors:
  - provsalt
  - muqsit
version: 1.2.5
mcpe-protocol: [431, 437]
website: moonlightpe.com
main: provsalt\lightningdeath\Loader
permissions:
  lightningdeath.bypass:
    default: false
